name: chronoburn
version: '2.3.7'
summary: ChronoBurn is a real-time calorie counter
description: |
  ChronoBurn is a real-time calorie counter that simulates the human metabolism. 
    
  Visit the free web version at https://chronoburn.com
  
confinement: strict
grade: stable

parts:
  chronoburn:
    source: .
    plugin: dump
    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpulse0
      - libxss1
      - libxtst6
    after:
      - desktop-gtk2

apps:
  chronoburn:
    icon: icon.png
    plugs:
      - bluez
      - browser-support
      - gsettings
      - home
      - mount-observe
      - network
      - network-bind
      - opengl
      - pulseaudio
      - unity7
      - desktop
      - desktop-legacy
      - wayland
      - x11
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
  
  